version: "3.9"
services:
  backend:
    build: ./backend
    depends_on:
      - db
    links:
      - db
    ports:
      - '8000:80'
    environment:
      - PORT=80
      - DB=db
    env_file:
      - backend/.env
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  frontend:
    build:
      context:  ./frontend/
      dockerfile: Dockerfile
    depends_on:
      - backend
    links:
      - backend
    ports:
      - 80:3000
    restart: unless-stopped
volumes:
  my-db:
